Remove broken work-around for specifying build platforms for the operator image
operator-framework/ansible-operator-plugins pull request #49
Opened 2024-01-08 19:07 UTC by rooftopcellist

**Description of the change:**

Resolves: https://github.com/operator-framework/ansible-operator-plugins/issues/48

Currently, the `make docker-buildx` target does not work for ansible operators as we found out in the github.com/ansible/eda-server-operator.  See details here:
* https://github.com/ansible/eda-server-operator/pull/158

**Motivation for the change:**

Users want to be able to build ansible operators for platforms other than the one on the build system or local machine.  

cc @everettraven

2024-01-09 14:31 UTC, everettraven requested changes
Thanks for creating this PR @rooftopcellist !

One thing blocking this PR is that this only updates the testdata which is generated files and will be overwritten. This also means that _only_ this testdata would be updated and future project scaffolding won't be fixed. Instead, the change should be made in https://github.com/operator-framework/ansible-operator-plugins/blob/bbe095f316eda31423b18b8d5e6bafddd524f558/pkg/plugins/ansible/v1/scaffolds/internal/templates/makefile.go#L106-L121 and the testdata regenerated with `make generate`

2024-01-11 04:58 UTC, rooftopcellist commented
Thanks for the review @everettraven !  I just pushed the change to the `makefile.go`, I left in the diff for the testdata as I figured it wouldn't hurt.  

Let me know if any other changes are needed.

2024-01-11 14:02 UTC, everettraven approved these changes
Thanks @rooftopcellist ! LGTM

2024-01-11 22:20 UTC, rooftopcellist commented
@everettraven I think these CI failures are un-related and just need a re-kick, I could be wrong though.

2024-01-12 14:14 UTC, everettraven commented
@rooftopcellist A re-kick will still fail as this is a build issue with the base image due to a vulnerability in one of the python packages. I'll create a separate PR to fix it and once that is in I should be able to close and reopen this PR so it picks up those changes in CI

2024-01-22 16:41 UTC, merged