in case of failure, we want to update the error to latest run
operator-framework/ansible-operator-plugins pull request #62
Opened 2024-03-12 14:11 UTC by gaelgatelement

Its required for status to continue to update its message, despite the playbook remaining in a Failure mode.

Without this, the admin only sees the first error that the playbook met, and never see any new errors than happens has more reconciles continue to fail on distinct steps.

2024-03-14 17:28 UTC, everettraven requested changes
I think the change generally looks good and make sense, but would you mind adding some more unit tests to make sure the change is functioning as expected?

2024-03-14 17:50 UTC, gaelgatelement commented
> I think the change generally looks good and make sense, but would you mind adding some more unit tests to make sure the change is functioning as expected?

Certainly, let me find some time next week. I have other PR's in preparation as well.

2024-04-23 09:41 UTC, gaelgatelement commented
Alright, with a bit of delay, but I finally found time to implement a test for this.

2024-10-17 07:47 UTC, gaelgatelement commented
Hello,

Can we try to get this fix merged? Can I do anything to help?

Thanks

2024-10-22 16:12 UTC, merged